// content/curriculum.ts
import { Lesson } from '@/types'

export const LESSONS: Record<number, Lesson> = {
  1: {
    keyLine: 'E + R = O',
    headline: 'You control more than you think.',
    body: 'Every day something happens that you did not choose. This program trains the one part you always control — your Response.',
    note: 'Before starting: ask your child what usually happens when things go wrong at home. Listen without correcting. That question sets up E+R=O perfectly.',
    recap: null,
    chunks: [
      { visual: 'ero-hero', teach: 'Three letters. One big idea. E is the Event — something happens. R is your Response — what you do next. O is the Outcome — what comes from it. The only part you always control is the R.', check: { q: 'Which part do YOU always control?', opts: ['The Event — what happens', 'The Response — what you do'], answer: 1 } },
      { teach: 'The Event is just what happened. You did not always choose it. But your Response? That is completely yours. Nobody can take it away from you.', check: { q: 'Your snack falls on the floor. That is the...', opts: ['Event', 'Response'], answer: 0 } },
      { visual: 'ero-example', teach: 'Here is the same Event with two different Responses — and two completely different Outcomes. Same thing happened. The R changed everything.' },
      { teach: 'Every time you train your R, you get stronger. Not just today — for the rest of your life. That is what this program is about.' },
    ],
    challenge: ['When something goes wrong this week, say out loud: That is the Event. What is my Response?', 'Try to name E, R, and O for one thing that happens.', 'Tell someone in your family what E+R=O means.'],
    seal: [{ q: 'In E+R=O, which part do YOU always control?', opts: ['The Event', 'The Response'], answer: 1 }, { q: 'E is the Event. O is the Outcome. What is R?', opts: ['Response', 'Reason'], answer: 0 }],
  },
  2: {
    keyLine: 'Own your space.',
    headline: 'You have 20 square feet. Use them.',
    body: 'Picture a box on the floor around you — about the size of a rug. Inside it? That is all you.',
    note: 'After the lesson: walk around the room together and literally point to your child\'s 20 square feet. Make it physical, not just a concept.',
    recap: { emoji: '⚡', title: 'Last week: Managing the R', points: ['Every day has Events you cannot control', 'You always control your Response', 'E + R = O'] },
    chunks: [
      { visual: 'sqft-image', teach: 'Two areas. Inside: things you control — your attitude, your words, your actions, how you respond. Outside: things you cannot control — other people, what happens around you. You can impact and influence outside. But you cannot control it.', check: { q: 'Which one lives inside your 20 square feet?', opts: ['What your sibling does', 'How YOU respond'], answer: 1 } },
      { teach: 'Strong people focus their energy on the inside — what they can actually change. They do not waste energy on what they cannot control.', check: { q: 'Your sibling is being loud. What CAN you control?', opts: ['How loud they are', 'How you respond'], answer: 1 } },
      { teach: 'Your 20 square feet travels with you everywhere. Your seat in the car. Your spot at the table. Your side of the room. Own it.' },
    ],
    challenge: ['Point to your 20 square feet right now and name one thing you control.', 'When something happens outside your space, say: Not in my 20 square feet.', 'Notice once when you tried to control something you cannot — and let it go.'],
    seal: [{ q: 'Which one is inside your 20 square feet?', opts: ['What your sibling does', 'How YOU respond'], answer: 1 }, { q: 'Outside your 20 square feet, you can...', opts: ['Control everything', 'Impact and influence — but not control'], answer: 1 }],
  },
  3: {
    keyLine: 'B. C. D.',
    headline: 'Three habits that keep you stuck.',
    body: 'When something goes wrong, there is an automatic move. Blame someone. Complain about it. Defend yourself. These habits keep you right where you are.',
    note: 'This week: when you catch BCD in yourself or anyone around you, name it calmly. No shame. Just shared language between you and your child.',
    recap: { emoji: '📦', title: 'Last week: Your 20 Square Feet', points: ['Inside = what you control', 'Outside = impact and influence, not control', 'Your 20 square feet goes everywhere with you'] },
    chunks: [
      { visual: 'bcd-prohibition', teach: 'Three letters that represent the three most common ways people react when things go wrong. Each one damages relationships, wastes energy, and keeps you stuck.' },
      { visual: 'bcd-tiles', teach: 'Three habits. B is Blaming — pointing at someone else. C is Complaining — saying what is wrong without fixing it. D is Defending — making excuses instead of owning it.', check: { q: 'It is not my fault — he started it! What is that?', opts: ['Blaming', 'Complaining'], answer: 0 } },
      { teach: 'BCD never solves anything. It damages relationships, keeps you stuck, and signals that someone else controls your outcome. The opposite is seeking resolution.', check: { q: 'This is so unfair, I hate this. What is that?', opts: ['Defending', 'Complaining'], answer: 1 } },
      { teach: 'Venting is BCD. If you bring something up to fix it — that is resolution. If you bring it up to vent — that is BCD. Mindset matters. Seek resolution.' },
    ],
    challenge: ['When you hear BCD this week — even if it is yours — name it out loud.', 'Try to catch yourself blaming, complaining, or defending once.', 'Tell a family member what BCD stands for.'],
    seal: [{ q: 'What does BCD stand for?', opts: ['Blaming, Complaining, Defending', 'Building, Creating, Deciding'], answer: 0 }, { q: 'Venting is...', opts: ['Seeking resolution', 'BCD'], answer: 1 }],
  },
  4: {
    keyLine: 'Catch it. Name it. Choose differently.',
    headline: 'Now put it to work.',
    body: 'Knowing what BCD is and catching yourself doing it are two different things. This week is about practice.',
    note: 'Model it yourself this week: when you catch yourself doing BCD, say it out loud. I was just defending there. Let me try that differently. That gives your child permission to do the same.',
    recap: { emoji: '🚫', title: 'Last week: No BCD', points: ['BCD never solves anything — it keeps you stuck', 'Venting is BCD. Seeking resolution is the opposite.', 'Choosing differently takes more strength'] },
    chunks: [
      { teach: 'The first step is just noticing. When you catch yourself doing BCD — that is a win. It means you are paying attention. Most people never even notice.', check: { q: 'I could not clean my room because my sibling was bothering me. What is that?', opts: ['Defending', 'Blaming'], answer: 0 } },
      { visual: 'bcd-to-resolution', teach: 'Here is the difference. BCD keeps you stuck. Resolution moves you forward. Look at what each one actually sounds like.' },
      { teach: 'Once you notice BCD, switch. Instead of this is so unfair — try what can I do right now? That one question changes where you end up.', check: { q: 'You get in trouble. Instead of blaming, you ask what you could do differently. Is that BCD?', opts: ['Yes it is', 'No it is not'], answer: 1 } },
      { teach: 'You will not catch it every time. Nobody does. But every time you catch it and choose resolution instead, you get stronger.' },
    ],
    challenge: ['When you catch BCD this week, ask: What can I do right now?', 'Try to turn one BCD moment into a different response.', 'At dinner, share one time you chose something different instead of BCD.'],
    seal: [{ q: 'When you catch BCD, the move is to...', opts: ['Ignore it and move on', 'Name it and choose differently'], answer: 1 }, { q: 'Instead of this is so unfair, try asking...', opts: ['Why does this always happen?', 'What can I do right now?'], answer: 1 }],
  },
  5: {
    keyLine: 'Discipline or Default.',
    headline: 'Every hard moment gives you a choice.',
    body: 'When something difficult happens, two paths show up. One is automatic. One is chosen. You decide which one runs.',
    note: 'Use Discipline and Default as a family lens from now on. Was that Discipline or Default? Ask it as a question, not a correction. Make it shared language.',
    recap: { emoji: '✅', title: 'Last week: No BCD in Action', points: ['Catching BCD is a win — you are paying attention', 'Switch from unfair to what can I do now?', 'Every catch makes you stronger'] },
    chunks: [
      { visual: 'character-bot', title: 'Default 🤖', traits: ['Impulsive', 'Autopilot', 'Resistant'], teach: 'Default shows up every time something goes wrong. It reacts before thinking. It does whatever is comfortable. It avoids anything hard. It is not chosen — it just happens when you are not paying attention.', check: { q: 'When Default is running, you...', opts: ['Think before you act', 'Just react without thinking'], answer: 1 } },
      { visual: 'character-tiger', title: 'Discipline 🐯', traits: ['Intentional', 'Purposeful', 'Skillful'], teach: 'Discipline is intentional — thinks before acting. Purposeful — knows why it is choosing. Skillful — gets better every time. This is the version of you that you are proud of.', check: { q: 'Discipline is...', opts: ['Impulsive and automatic', 'Intentional and purposeful'], answer: 1 } },
      { visual: 'radio', teach: 'Your brain is like a radio. Default runs the Default Station — plays whatever comes first. Discipline runs the Discipline Station — you choose what plays. You always control the dial.', check: { q: 'Who controls which station plays?', opts: ['Default decides', 'You decide'], answer: 1 } },
      { visual: 'comparison', teach: 'Here is the difference side by side. Default or Discipline. Every time something hard happens, you pick which one shows up.' },
      { teach: 'Default is not bad on purpose. It is just automatic. Every time you pick Discipline, you get a little stronger at it.', check: { q: 'You lose a game and feel like throwing something. Discipline would...', opts: ['React and throw it', 'Take a breath and choose'], answer: 1 } },
    ],
    challenge: ['When something hard happens, ask out loud: Default or Discipline?', 'Try to catch Default three times before it takes over.', 'Tell a parent when you chose Discipline this week.'],
    seal: [{ q: 'Discipline means being intentional, purposeful, and...', opts: ['Impulsive', 'Skillful'], answer: 1 }, { q: 'When you drift to autopilot and resist change, you are in...', opts: ['Discipline', 'Default'], answer: 1 }],
  },
  6: {
    keyLine: 'Stop. Breathe. Then choose.',
    headline: 'One second changes everything.',
    body: 'When something hard happens, your brain wants to react right now. Pressing Pause gives you that one second back — and that second is everything.',
    note: 'Watch for your child\'s physical signals this week. When you see them escalating, say quietly: I think I see your pause signal. Help them name it before it fires.',
    recap: { emoji: '🎯', title: 'Last week: Discipline vs. Default', points: ['Default: impulsive, autopilot, resistant', 'Discipline: intentional, purposeful, skillful', 'You control the radio dial — you pick the station'] },
    chunks: [
      { visual: 'tiger-pause-img', teach: 'Pressing Pause is the move. One breath between the Event and your Response. That is the whole skill. The tiger knows when to stop and when to go.' },
      { visual: 'body-cues', teach: 'Your body gives you signals when Default is about to take over. Face gets hot. Chest gets tight. Voice gets loud. These are your cue to Press Pause.', check: { q: 'Your face gets hot and you feel like yelling. Time to...', opts: ['React fast', 'Press Pause'], answer: 1 } },
      { visual: 'three-pause', teach: 'There are three times you can pause. You do not need all three every time — mix and match what the moment needs.', check: { q: 'The Situational Pause happens...', opts: ['Before the Event', 'Right in the moment'], answer: 1 } },
      { visual: 'character-bot', title: 'Default 🤖', subtitle: 'Reacts the second something hard happens. No breath. No pause. Just go — and it almost always makes things worse.', teach: 'Default never pauses. It reacts immediately. That is why things escalate so fast.', check: { q: 'Default\'s move when something hard happens...', opts: ['Take a breath first', 'React immediately'], answer: 1 } },
      { visual: 'character-tiger', title: 'Discipline 🐯', subtitle: 'Feels the signal — face hot, chest tight — then takes one breath. That one breath is everything.', teach: 'One breath. That is the whole skill. One breath before you respond is how you stop Default from running the show.' },
    ],
    challenge: ['When you feel your face get hot — that is your Pause signal. Use it.', 'Practice one breath before responding to something hard.', 'Try all three pauses this week: plan ahead once, pause in the moment once, look back once.'],
    seal: [{ q: 'What are the three types of Pause?', opts: ['Proactive, Situational, Reflective', 'Before, After, Never'], answer: 0 }, { q: 'Which Pause happens right in the middle of the Event?', opts: ['Proactive', 'Situational'], answer: 1 }],
  },
  7: {
    keyLine: 'Self Talk: own the cycle.',
    headline: 'Your brain is always running a cycle. You choose which version.',
    body: 'Before you act, you focus on something. That focus drives your self-talk. Your self-talk drives how you feel. How you feel drives what you do. You own all of it.',
    note: 'Share your own Mindset Cycle this week. My brain was focused on the wrong thing on the drive home. Normalizing it makes it easier for your child to spot it in themselves.',
    recap: { emoji: '⏸️', title: 'Last week: Press Pause', points: ['Your body gives you signals: face hot, chest tight', 'One breath before you respond — that is the whole skill', 'Three pauses: Proactive, Situational, Reflective'] },
    chunks: [
      { visual: 'mindset-cycle', teach: 'Four parts. They run in order, every time. Focus drives what you say to yourself. Self-Talk drives how you feel. Feelings drive what you do. Change what you focus on — everything else follows.', check: { q: 'In the Mindset Cycle, what comes first?', opts: ['Feelings', 'Focus'], answer: 1 } },
      { visual: 'thought-card', teach: 'Default Station focuses on what is wrong, what is not fair, what you cannot control. Discipline Station flips it. Focus on what you can do. The feelings follow.', check: { q: 'I cannot do this is playing on which station?', opts: ['Discipline Station', 'Default Station'], answer: 1 } },
      { teach: 'You cannot directly control how you feel. But you can control what you focus on and what you say to yourself. Work those two — the feelings follow.', check: { q: 'To change how you feel, start by changing your...', opts: ['Focus and Self-Talk', 'Feelings directly'], answer: 0 } },
      { visual: 'instead-of-7', pairs: [{ before: "I can't do this.", after: "I haven't figured this out yet." }, { before: 'This is too hard.', after: 'Hard things make me stronger.' }, { before: 'I always mess up.', after: "I'm still learning." }], teach: 'Three reframes. Tap through them. The goal is not to lie to yourself — it is to tell yourself a better truth.' },
    ],
    challenge: ['When the voice goes negative, say: Switching stations. What is my focus right now?', 'Replace one unhelpful thought with a better truth this week.', 'Before something hard, tell yourself: I can handle this. Say it out loud.'],
    seal: [{ q: 'In the Mindset Cycle, Focus drives Self-Talk drives Feelings drives...', opts: ['More Self-Talk', 'Action'], answer: 1 }, { q: 'To change how you feel, the best move is to change your...', opts: ['Focus first', 'Feelings directly'], answer: 0 }],
  },
  8: {
    keyLine: 'Do it anyway.',
    headline: 'Step Up: take the action the moment requires.',
    body: 'R1 and R2 are preparation. R3 is execution. The whole reason you press pause and get your mind right is so you can step up when it counts.',
    note: 'When they resist something hard this week, ask: Is that Default or Discipline making that call? Then step back and let them choose.',
    recap: { emoji: '🧠', title: 'Last week: Get Your Mind Right', points: ['Focus drives Self-Talk drives Feelings drives Action', 'Default Station focuses on what is wrong', 'You control the dial — switch stations'] },
    chunks: [
      { visual: 'step-up-four', teach: 'Four ways to Step Up. You do not have to do all four at once. Win the Moment first. Stack them.', check: { q: 'Win the Moment means...', opts: ['Winning the whole year', 'The next 5 minutes only'], answer: 1 } },
      { visual: 'character-bot', title: 'Default 🤖', subtitle: 'Sits down and waits to feel ready. That feeling never comes. So Default stays stuck.', teach: 'Default always waits for the feeling first. The feeling never arrives — so Default never goes.', check: { q: "Default's move when something feels hard...", opts: ['Do it anyway', 'Wait until it feels easy'], answer: 1 } },
      { visual: 'character-tiger', title: 'Discipline 🐯', subtitle: 'Feels nervous. Steps up anyway. That is the whole skill. Bravery comes from going, not from feeling ready.', teach: 'Discipline does not wait to feel brave. It steps up while still nervous. Every time it does, it gets a little bigger than the hard thing.' },
    ],
    challenge: ['Do one thing this week you really do not feel like doing — and do it anyway.', 'When you want to quit, say: I am doing it anyway. Then do it.', 'Tell your family one time you Stepped Up this week.'],
    seal: [{ q: 'Win the Moment means...', opts: ['Winning the whole year', 'The next 5 minutes only'], answer: 1 }, { q: 'Step Up to Predictable means...', opts: ['Reacting when hard things happen', 'Pre-planning your R before the E arrives'], answer: 1 }],
  },
  9: {
    keyLine: 'New plan. Same goal.',
    headline: 'When what you are doing is not working — change what you are doing.',
    body: 'Something always changes. Plans fall apart. The best responders do not double down and hope harder. They adjust, adapt, and find the next way.',
    note: 'Model it this week: when something does not go as planned, say out loud — I am going to be responsive here and try a different way. Show it before you teach it.',
    recap: { emoji: '💪', title: 'Last week: Step Up', points: ['Win the Moment: next 5 minutes only', 'Step Up to Predictable: pre-plan your R', 'Discipline goes even while nervous'] },
    chunks: [
      { visual: 'adjust-three-ways', teach: 'Three ways to adjust. You do not need all three every time. Match the tool to what the moment actually needs.', check: { q: 'Being Responsive means...', opts: ['Waiting until things get better on their own', 'Adjusting to what actually changed — even if you did not ask for it'], answer: 1 } },
      { visual: 'change-conditions', teach: 'Every real adjustment starts with three things. Open. Aware. Willing. If any one of those is missing, you will not change — even when you know you should.', check: { q: 'To adjust, you need to be Open, Aware, and...', opts: ['Right', 'Willing'], answer: 1 } },
      { visual: 'plan-list', teach: 'When Plan A falls apart, there is always a next move. The question is never why did this happen. The question is always: what do I do now?', check: { q: 'Plans change. The first question is...', opts: ['Why does this always happen to me?', 'What do I do now?'], answer: 1 } },
      { visual: 'instead-of-9', pairs: [{ before: "This isn't fair!", after: 'What can I try differently?' }, { before: "I don't want to change!", after: 'Okay. What is the new plan?' }, { before: 'Why does this always happen?', after: 'What do I do now?' }], teach: 'Watch the difference between what Default says and what Discipline says when things change.' },
      { visual: 'character-bot', title: 'Default 🤖', subtitle: 'Doubles down. Blames the change. Does it harder and louder. That is not adjusting — that is just failing with more effort.', teach: 'Default keeps doing the same thing and expects a different result. It blames the change instead of changing the response.' },
      { visual: 'character-tiger', title: 'Discipline 🐯', subtitle: 'Tries something different. Does not blame the change. Asks: what do I do now? Steps into the discomfort of trying a new way.', teach: 'Discipline changes the response when the response is not working. It does not double down. It adjusts.' },
    ],
    challenge: ['When something does not go as planned, ask: Am I open, aware, and willing to adjust?', 'Try one of the three ways this week — be responsive, be proactive, or try something completely different.', 'Find one Instead of saying... try saying... moment at home.'],
    seal: [{ q: 'What are the three ways to Adjust and Adapt?', opts: ['Responsive, Proactive, Transformative', 'React, Plan, Hope'], answer: 0 }, { q: 'When what you are doing is not working, you should...', opts: ['Keep doing it harder', 'Change what you are doing'], answer: 1 }],
  },
  10: {
    keyLine: 'Zoom out.',
    headline: 'What you focus on feels like everything.',
    body: 'When something bad happens, it is easy to zoom all the way in on just that one thing. That is not the whole picture.',
    note: 'When something frustrating happens, ask: On a scale of 1 to 10, how much will this matter next week? Help them calibrate their reaction to the actual size of the problem.',
    recap: { emoji: '🔄', title: 'Last week: Adjust & Adapt', points: ['When plans change — find a new way', 'Ask three words: What do I do now?', 'Options always exist. Find the next one.'] },
    chunks: [
      { visual: 'zoom-card', teach: 'Zoomed in: one bad moment fills your whole view. Zoomed out: that same moment is actually small. Lots of good stuff is still here.', check: { q: 'You spill your drink and it ruins your whole night. You are...', opts: ['Seeing the full picture', 'Zoomed in too far'], answer: 1 } },
      { teach: 'Ask yourself: will this matter next week? Next year? If the answer is no — that moment does not deserve all your energy right now.', check: { q: 'A sibling took your spot on the couch. Next week, will you care?', opts: ['Yes, a lot', 'Probably not'], answer: 1 } },
      { teach: 'Big reactions to small things drain your energy. Zoom out. Save it for what actually matters.' },
    ],
    challenge: ['When something goes wrong, ask: Will I care about this next week? If no — let it go.', 'Notice once when you were zoomed in too far. Then zoom out.', 'Tell someone when you saved your energy instead of spending it on something small.'],
    seal: [{ q: 'When one small thing feels HUGE, you are...', opts: ['Seeing the full picture', 'Zoomed in too far'], answer: 1 }, { q: 'Zooming out means asking...', opts: ['Who started it?', 'Will I care about this next week?'], answer: 1 }],
  },
  11: {
    keyLine: 'The brain believes what you tell it.',
    headline: 'You talk to yourself all day long. Make it count.',
    body: 'That voice is running all the time — and what it says changes everything. You can preload it before the hard moment ever arrives.',
    note: 'Ask your child what they tell themselves before something hard. Share yours too. Make self-talk something your family talks about openly.',
    recap: { emoji: '🔍', title: 'Last week: Focus Frame', points: ['Zoom in too far and one bad moment takes over', 'Ask: will this matter next week?', 'Save your energy for what matters'] },
    chunks: [
      { visual: 'thought-card', teach: 'Default Station shuts doors. Discipline Station opens them. The key insight: you can preload your response — decide what the voice will say BEFORE the hard moment comes.', check: { q: 'I always mess everything up. That voice is on...', opts: ['Discipline Station', 'Default Station'], answer: 1 } },
      { teach: 'You do not have to lie to yourself. Just tell yourself a better truth — one that is honest AND keeps a door open. This is hard AND I can handle it.', check: { q: 'Which one keeps the door open?', opts: ['I cannot do this', 'I have not figured this out yet'], answer: 1 } },
      { teach: 'Practice your preloaded response out loud before you need it. The brain believes what you tell it — so tell it something that helps.' },
      { visual: 'instead-of-11', pairs: [{ before: "I'm going to mess up.", after: 'I can handle this.' }, { before: 'Nobody will like it.', after: 'I can give it my best.' }, { before: "I don't want to try.", after: 'I can be brave and still be nervous.' }], teach: 'Preload one of these before the hard moment arrives this week.' },
    ],
    challenge: ['Pick one hard thing coming this week. Preload your response before it arrives.', 'Replace one station from Default to Discipline using the I can handle this phrase.', 'Tell a parent one thing you preloaded this week.'],
    seal: [{ q: 'Preloading means...', opts: ['Deciding what you will say after the hard moment', 'Deciding what you will say BEFORE the hard moment'], answer: 1 }, { q: 'The brain believes what you tell it. So tell it...', opts: ['What you are afraid of', 'Something that keeps the door open'], answer: 1 }],
  },
  12: {
    keyLine: 'Your R is an E for others.',
    headline: 'What you do in your 20 square feet ripples out.',
    body: 'Your R becomes their E. Every Response you make is an Event for the people around you. What you do in your 20 square feet ripples outward — good or bad.',
    note: 'Ask your child: who noticed something kind you did this week without being asked? Small consistent actions build the culture of your family.',
    recap: { emoji: '💬', title: 'Last week: Power of Self Talk', points: ['Preload before the hard moment arrives', 'The brain believes what you tell it', 'Replace Default Station with a better truth'] },
    chunks: [
      { visual: 'ripple-card', teach: 'One choice. It lands in your 20 square feet. Then it spreads. To your sibling. To your parent. To your school. Your R is always an E for someone else.' },
      { teach: 'You do not get to choose whether your choices affect others. You only get to choose how. Every response either adds to or subtracts from the people around you.', check: { q: 'Your response affects the people around you...', opts: ['Only sometimes', 'Every single time'], answer: 1 } },
      { visual: 'character-tiger', title: 'Discipline 🐯', subtitle: 'Notices the opportunity to make a difference. Shows up. Adds to the people nearby instead of subtracting.', teach: 'Making a difference does not mean big gestures. It means showing up in your 20 square feet consistently — and letting that ripple.' },
      { visual: 'activity-prompt', teach: 'This week: find one moment to make a difference in someone else\'s 20 square feet. Your sibling. A parent. A friend at school. Do not announce it. Just do it.' },
    ],
    challenge: ['Find one moment to make a difference this week — without being asked.', 'When you respond well to something hard, notice that it is an E for the people around you.', 'Tell your family one time your R became their E in a good way.'],
    seal: [{ q: 'Your R becomes their...', opts: ['O', 'E'], answer: 1 }, { q: 'Making a difference means...', opts: ['Big dramatic moments', 'Consistent choices in your 20 square feet'], answer: 1 }],
  },
  13: {
    keyLine: 'Practice makes permanent.',
    headline: 'These skills are yours now. Keep building them.',
    body: 'Every R Factor skill grows with repetition. The goal is not perfection. The goal is making Discipline your default — so when pressure comes, it just shows up.',
    note: 'Celebrate the finish. Print the certificate. Frame it. This is 13 weeks of real work. Let the moment land. Then ask: which skill do you want to keep building?',
    recap: { emoji: '⭐', title: 'Last week: Make a Difference', points: ['Your R is always an E for someone else', 'Every response adds or subtracts', 'Small consistent choices ripple outward'] },
    chunks: [
      { visual: 'skill-bar', teach: 'Every R Factor skill grows with repetition. Press Pause. Get Your Mind Right. Step Up. Adjust. They all started small. They grow every time you practice on purpose.', check: { q: 'Skills get stronger when you...', opts: ['Wait until you need them', 'Practice them on purpose'], answer: 1 } },
      { teach: 'Here is how to practice on purpose: pick one R skill this week, use it three times, and notice what happens. That is deliberate practice. That is how skills move from something you do into who you are.', check: { q: 'You Pressed Pause three times this week. Is that Building Skill?', opts: ['Yes', 'No'], answer: 0 } },
      { teach: 'Every time something does not go the way you wanted, ask one question: what is my R next time? That is how you use failure as feedback instead of letting it stop you. Default gives up. Discipline uses the miss to get better.' },
      { teach: 'When things get hard — when you are tired, nervous, or under pressure — you do not rise to the occasion. You fall back to your habits. Train the right habits now, and when pressure comes, Discipline shows up automatically.' },
    ],
    challenge: ['Pick one R Factor skill and practice it three times on purpose this week.', 'When something does not go well, ask: what is my R next time?', 'Tell your family which skill you are most proud of building over 13 weeks.'],
    seal: [{ q: 'Under pressure, you fall back on your...', opts: ['Best intentions', 'Habits'], answer: 1 }, { q: 'Failure is...', opts: ['A reason to stop', 'Feedback to get better'], answer: 1 }],
  },
}
